---
baseURL: https://main--celebrated-cannoli-fa0a3d.netlify.app/
languageCode: en-us
title: Dr. Vikram Uttam Patil
theme: piko
paginate: "9"
copyright: A template by [Heksagon](https://www.heksagon.net "Your most friendly developer")
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Ganesh Patil
  description: Your website description
  math: false
  images:
    - "/uploads/og.webp"
  label:
    title: _Dr. Vikram Uttam Patil_
    text: Welcome to Dr. Vikram Uttam Patil
    lightNavIcon: /uploads/sun.svg
    darkNavIcon: /uploads/zap.svg
    iconHeight: "35"
    iconWIdth: "35"
  comments: false
  mainSections:
    - blog
  ShowShareButtons: false
  ShowCodeCopyButtons: false
  ShowRelated: false
  CookieNotice:
    We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /uploads/zap.svg
    favicon16x16: /uploads/zap.svg
    favicon32x32: /uploads/zap.svg
    apple_touch_icon: /uploads/zap.svg
    safari_pinned_tab: /uploads/zap.svg
  ShowReadingTime: false
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle:
    heroTitle: Dr. Vikram Uttam Patil
    heroDescription: Is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra.
    heroCTAPrimaryText: Our services & specialties
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact Me
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/1.jpg"
    # Blog Section
    disableBlogSection: false
    blogTitle: Our services & specialties
    blogDescription: Dr. Vikram Uttam Patil is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra.
    seeMoreText: More Posts
    # About Section
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: Top Gastroenterologist, hepatologist and interventional endoscopist
    aboutImgUrl: "vicky.jpeg"
    aboutContent: Dr. Vikram Uttam Patil is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra. He has done more than 3000 endoscopy which includes- Gastroscopy Colonoscopy, Enteroscopy, ERCP, EUS, Manometry and interventional therapeutics procedures. He is currently working at Viswaraj Multispecialty Hospital, Loni Kalbhor, Pune. He has published 10+ articles in various national and international journals.

    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Awards
    portfolioDescription: Prize awarded to Dr. Vikram Uttam Patil is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra.
    portfolio:
      - imageUrl: /awards/Prize 1.jpeg
        alt: # image alt for better SEO
        description: Award One.
        websiteUrl: #
      - imageUrl: /awards/prize 2.jpeg
        alt: # image alt for better SEO
        description: Award Two.
        websiteUrl: #
      - imageUrl: /awards/prize 3.jpeg
        alt: # image alt for better SEO
        description: Award Three.
        websiteUrl: #
      - imageUrl: /awards/prize4.jpg
        alt: # image alt for better SEO
        description: Award Four.
        websiteUrl: #
      - imageUrl: /awards/prize5.jpeg
        alt: # image alt for better SEO
        description: Award Five.
        websiteUrl: #
    # Search Options (https://fusejs.io/)
    # Testimonial Section
    disableTestimonialSection: false
    testimonialTitle: Testimonial
    testimonialDescription: Prize awarded to Dr. Vikram Uttam Patil is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra.
    testimonial:
      - imageUrl: /awards/Prize 1.jpeg
        alt: # image alt for better SEO
        description: Best doctor for any digestive issues in pune.
        websiteUrl: #
      - imageUrl: /awards/prize 2.jpeg
        alt: # image alt for better SEO
        description: Best doctor for any digestive issues in pune.
        websiteUrl: #
      - imageUrl: /awards/prize 3.jpeg
        alt: # image alt for better SEO
        description: Best doctor for any digestive issues in pune.
        websiteUrl: #
      - imageUrl: /awards/prize4.jpg
        alt: # image alt for better SEO
        description: Best doctor for any digestive issues in pune.
        websiteUrl: #
      - imageUrl: /awards/prize5.jpeg
        alt: # image alt for better SEO
        description: Best doctor for any digestive issues in pune
        websiteUrl: #
    # Search Options (https://fusejs.io/)
    cover:
      imageUrl: /uploads/portfolio-1.webp
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
      - title
      - permalink
      - summary
      - content
  plugins:
    css:
      - link: plugins/css/pico.min.css
    js:
      - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
    - name: Blog
      title: Services
      pre: book
      url: "/blog"
      weight: "20"
    - name: Search
      title: Search
      pre: search
      url: "/search"
      weight: "30"
    - name: Procedures
      title: Procedures
      pre: ""
      url: ""
      weight: "40"
    - name: Members Of
      title: Members Of
      pre: "/membersOf"
      url: ""
      weight: "50"
    - name: Contact
      title: Contact
      pre: mail
      url: "/contact"
      weight: "60"
  search: # Search page's quick links
    - name: Categories
      title: Categories
      url: "/categories"
      weight: "10"
    - name: Archives
      title: Archives
      url: "/archives"
      weight: "20"
    - name: Tags
      title: Tags
      url: "/tags"
      weight: "30"
