baseURL = "https://main--celebrated-cannoli-fa0a3d.netlify.app/"
languageCode = "en-us"
title = "Dr. Vikram Uttam Patil"
theme = "piko"
paginate = "20"
copyright = ''
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false

[params]
env = "production"
author = ""
description = "Your website description"
math = false
images = [ "/uploads/og.webp" ]
comments = false
mainSections = [ "blog" ]
ShowShareButtons = false
ShowCodeCopyButtons = false
ShowRelated = false
CookieNotice = "We use cookies to improve your experience on our site and to show you relevant advertising."
CookieLink = "/legal/privacy/#cookies-and-web-beacons"
CookieButton = "Cookies Policy"
disableAnchoredHeadings = false
ShowReadingTime = false
ShowBreadCrumbs = true

[params.analytics.google]

[params.analytics.yandex]

[params.analytics.bing]

  [params.label]
  title = "_Dr. Vikram Uttam Patil_"
  text = "Welcome to Dr. Vikram Uttam Patil"
  lightNavIcon = "/uploads/sun.svg"
  darkNavIcon = "/uploads/zap.svg"
  iconHeight = "35"
  iconWIdth = "35"

  [params.assets]
  disableFingerprinting = false
  favicon = "/uploads/zap.svg"
  favicon16x16 = "/uploads/zap.svg"
  favicon32x32 = "/uploads/zap.svg"
  apple_touch_icon = "/uploads/zap.svg"
  safari_pinned_tab = "/uploads/zap.svg"

  [params.homepage]
  disableHeroSection = false
  heroUpperTitle = "Dr. Vikram Uttam Patil "
  heroTitle = "MBBS, DNB(Medicine), DrNB (Gastroenterologist) MNAMS"
  heroDescription = ""
  heroDescription1 = "Gastroenterologist, Liver specialist and Interventional Endoscopist."
  heroCTAPrimaryText = "Our services & specialties"
  heroCTAPrimaryUrl = "/blog/"
  heroCTASecondaryText = "Contact Me"
  heroCTASecondaryUrl = "/contact/"
  heroBackgroundImage = "/uploads/1.jpg"
  disableBlogSection = false
  blogTitle = "Our services & specialties"
  blogDescription = "Dr. Vikram Uttam Patil is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra."
  seeMoreText = "More Services Offered"
  disableAboutSection = false
  aboutTitle = "About"
  aboutDescription = "Top Gastroenterologist, hepatologist and interventional endoscopist"
  aboutImgUrl = "vicky.jpeg"
  aboutContent = "Dr. Vikram Uttam Patil is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra. He has done more than 3000 endoscopy which includes- Gastroscopy, Colonoscopy, Enteroscopy, ERCP, EUS, Manometry and interventional therapeutics procedures. He is currently working at Vishwaraj Multispecialty Hospital, Loni Kalbhor, Pune. He has published 12+ articles in various national and international journals."
  disablePortfolioSection = false
  portfolioTitle = "Awards & Recognitions"
  portfolioDescription = "Prize awarded to Dr. Vikram Uttam Patil is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra."
  disableTestimonialSection = true
  testimonialTitle = "Testimonial"
  testimonialDescription = "Prize awarded to Dr. Vikram Uttam Patil is a top Gastroenterologist, hepatologist and interventional endoscopist practicing in Pune, Maharashtra."

    [[params.homepage.portfolio]]
    imageUrl = "/awards/prize7.jpg"
    description = "Winner of Medical Quiz Competition, APICON 2017."

    [[params.homepage.portfolio]]
    imageUrl = "/awards/Prize 1.jpeg"
    description = "First Prize in Case Presentation, 4th Bangalore Neuro Update 2017."

    [[params.homepage.portfolio]]
    imageUrl = "/awards/prize8.jpg"
    description = "Oral Platform and Poster Presentation, APICON 2018."
    
    [[params.homepage.portfolio]]
    imageUrl = "/awards/prize 3.jpeg"
    description = "First Prize in Case Presentation at 6th Gastroenterology Summit 2021."
    
    [[params.homepage.portfolio]]
    imageUrl = "/awards/prize9.jpg"
    description = "Case Presentation at GYM 2022."

    [[params.homepage.portfolio]]
    imageUrl = "/awards/prize 2.jpeg"
    description = "Endoscopy Quiz Winner, Gastrocon 2022."

    [[params.homepage.portfolio]]
    imageUrl = "/awards/prize4.jpg"
    description = " First Prize in Video Contest at ERCP LIVE, Mumbai 2023"

    [[params.homepage.portfolio]]
    imageUrl = "/awards/prize5.jpg"
    description = "Asian EUS Training Completion Certificate,Mumbai 2023."

    [[params.homepage.portfolio]]
    imageUrl = "/awards/Prize6.jpg"
    description = "Best Thesis Award by ISGCON 2023, Bangalore."

    [[params.homepage.portfolio]]
    imageUrl = "/awards/prize10.jpg"
    description = "Poster Presentation at Digestive Disease Week, Chicago 2023."

    [[params.homepage.testimonial]]
    imageUrl = "/awards/Prize 1.jpeg"
    description = "Best doctor for any digestive issues in pune."

    [[params.homepage.testimonial]]
    imageUrl = "/awards/prize 2.jpeg"
    description = "Best doctor for any digestive issues in pune."

    [[params.homepage.testimonial]]
    imageUrl = "/awards/prize 3.jpeg"
    description = "Best doctor for any digestive issues in pune."

    [[params.homepage.testimonial]]
    imageUrl = "/awards/prize4.jpg"
    description = "Best doctor for any digestive issues in pune."

    [[params.homepage.testimonial]]
    imageUrl = "/awards/prize5.jpg"
    description = "Best doctor for any digestive issues in pune"

    [params.homepage.cover]
    imageUrl = "/uploads/portfolio-1.webp"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = "0"
  distance = "1000"
  threshold = "0.4"
  minMatchCharLength = "0"
  keys = [ "title", "permalink", "summary", "content" ]

[[params.plugins.css]]
link = "plugins/css/pico.min.css"

[[params.plugins.js]]
link = "plugins/js/feather.min.js"

[[menus.main]]
name = "Blog"
title = "Services"
pre = "book"
url = "/blog"
weight = "20"

[[menus.main]]
name = "Search"
title = "Search"
pre = "search"
url = "/search"
weight = "30"

[[menus.main]]
name = "Contact"
title = "Contact"
pre = "mail"
url = "/contact"
weight = "80"

[[menus.main]]
name = "Gallery"
title = "Gallery"
pre = "video"
url = "/videos"
weight = "70"

[[menus.main]]
name = "Procedures"
title = "Procedures"
pre = "video"
url = "/procedures"
weight = "70"

[[menus.main]]
name = "Member  Of"
title = "Member Of"
pre = "book"
url = "/membersof"
weight = "50"

[[menus.search]]
name = "Categories"
title = "Categories"
url = "/categories"
weight = "10"

[[menus.search]]
name = "Archives"
title = "Archives"
url = "/archives"
weight = "20"

[[menus.search]]
name = "Tags"
title = "Tags"
url = "/tags"
weight = "30"
